apiVersion: v1
kind: List  # can list several kubernetes resource types in a single yaml file
items:
- apiVersion: v1
  kind: Pod # ecommerce frontend pod
  metadata:
    name: ecommerce-ui
    labels:
      owner: zbio
      app: ecommerce-ui
  spec:
    containers:
    - name: frontend
      image: ecommerce-ui:v1
      stdin: true
      tty: true
      command:
      - "sh"
      - "-c"
      - "REACT_APP_API_URL=roost-controlplane:30081 npm start" #setting REACT_APP_API_URL env variable to backend's NodePort is imp
      ports:
        - containerPort: 3000
    
- apiVersion: v1
  kind: Service
  metadata:
    name: ecommerce-ui-svc
    labels:
      owner: zbio
      app: ecommerce
  spec:
    selector:
      app: ecommerce-ui
    type: NodePort
    ports:
    - name: frontend-port
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30080
      
- apiVersion: v1
  kind: Pod # ecommerce backend pod
  metadata:
    name: ecommerce-backend
    labels:
      owner: zbio
      app: ecommerce-backend
  spec:
    containers:
    - name: backend
      image: ecommerce:v1
      ports:
      - containerPort: 8080
      
- apiVersion: v1
  kind: Service
  metadata:
    name: ecommerce-svc
    labels:
      owner: zbio
      app: ecommerce
  spec:
    selector:
      app: ecommerce-backend
    type: NodePort
    ports:
    - name: backend-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30081
