proto:
	protoc greetpb/greet.proto --go_out=plugins=grpc:.
server:
	go run github.com/roost-io/examples/grpc-go/greeting/greet_server/
client:
	go run&&  gihub.com/roost-io/examples/grpc-go/greeting/greet_client/