FROM elasticsearch:7.5.1

# The author
LABEL author="Author Name"

# copy the configuration file into the container
#Elasticsearch comes with enough default config, if you wish to use a custom config, uncomment the following line. 
# COPY elasticsearch.yml /usr/share/elasticsearch/config

# expose the default Elasticsearch port
EXPOSE 9200