apiVersion: v1
kind: Pod
metadata:
  name: collab-fetcher
  labels:
    app: fetcher
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: fetcher
    image: fetcher:latest
    env:
    - name: STORAGE_DIR
      value: /app-store
    volumeMounts:
    - mountPath: /app-store
      name: article-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - name: fetcher-port
        containerPort: 8080
    imagePullPolicy: Never
  terminationGracePeriodSeconds: 0
  volumes:
  - name: article-storage
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: fetcher
  labels:
    owner: zbio
    managed-by: roost
spec:
  selector:
    app: fetcher
  ports:
  - name: fetch-svc-port
    port: 30047
    targetPort: 8080