FROM golang:alpine
#RUN apk add git g++ gcc
#RUN go get -v github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc \
#    github.com/opentracing/opentracing-go
#RUN apk del git 

# ADD zbclient /zbclient
# WORKDIR /zbclient
# #ADD . /go/src/github.com/ZB-io/zbio/client
# #WORKDIR /go/src/github.com/ZB-io/zbio/client

# ENTRYPOINT ./zbclient.sh
# CMD [default] 
 